name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      # Set Timezone
      - name: Set timezone to Jakarta
        run: |
          sudo timedatectl set-timezone Asia/Jakarta
          timedatectl

      # Set Current Date As Env Variable
      - name: Set current date as env variable
        run: echo "date_today=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      # Set App Name As Env Variable
      - name: Set repository name as env variable
        run: echo "repository_name=RvKernel Manager" >> $GITHUB_ENV

      # Set Up JDK
      - name: Set Up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      # Change wrapper permissions
      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      # Send start message to Telegram
      - name: Send start message to Telegram
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          DATE=$(date +"%Y-%m-%d")
          TIME=$(date +"%H:%M")
          curl -s -X POST https://api.telegram.org/bot${{ env.TELEGRAM_BOT_TOKEN }}/sendMessage \
          -d chat_id=${{ env.TELEGRAM_CHAT_ID }} \
          -d text="[$DATE]-[$TIME] Start build RvKernel Manager"
          echo "start_time=$(date +%s)" >> $GITHUB_ENV

      # Run Tests Build
      - name: Run gradle tests
        run: ./gradlew test

      # Run Build Project
      - name: Build gradle project
        run: ./gradlew build

      # Create APK Release
      - name: Build apk release project (APK) - ${{ env.main_project_module }} module
        run: ./gradlew assemble

      # Upload Artifact Build
      - name: Upload APK Release - ${{ env.repository_name }}
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.repository_name }} - ${{ env.date_today }} - APK release generated
          path: app/build/outputs/apk/fdroid/release/

      # Send finish message to Telegram
      - name: Send finish message to Telegram
        if: always()
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          start_time: ${{ env.start_time }}
        run: |
          DATE=$(date +"%Y-%m-%d")
          TIME=$(date +"%H:%M")
          end_time=$(date +%s)
          build_time=$((end_time - start_time))
          build_time_minutes=$((build_time / 60))
          build_time_seconds=$((build_time % 60))
          build_duration="${build_time_minutes}m ${build_time_seconds}s"
          status=${{ job.status }}
          curl -s -X POST https://api.telegram.org/bot${{ env.TELEGRAM_BOT_TOKEN }}/sendMessage \
          -d chat_id=${{ env.TELEGRAM_CHAT_ID }} \
          -d text="[$DATE]-[$TIME] Build RvKernel Manager ${status} in ${build_duration}"
